### PR TITLE
Add feature #103

### LINKED ISSUE #103: [Feature Request] Max Width/Height for pictures
Actualliy we can only specify a percent of the original image size we want. It would be great to have the ability to set a max Width and Max Height to have an image size independant of device camera resolution.

PS: Sory for my english but I think you will understand my request ;)

Thanks

### PR DESCRIPTION
**Pull request by jsmarcus**
This implements the changes @xeterixon made but on the current code
base.

Please take a moment to fill out the following:

Fixes #103 .

Changes Proposed in this pull request:
- Adds a Manual option to the PhotoSize enumeration
- Adds a ManualSize to PickMediaOptions

### CODE REVIEW

**Comment by xeterixon** [comment]
Sorry for being to lazy and not doing it myself... and thanks to you for doing it... ;)

**Comment by jamesmontemagno** [comment]
Nice :) will be looking into this this week, at conferences a bunch :)

**Comment by xeterixon** [comment]
Semi-offtopic: thanks your and Miguels session at build...

**Comment by jamesmontemagno** [comment]
I am going to pull in, but refactor a bit.

**Pull request merged**
