### PR TITLE
Multi gallery select

### PR DESCRIPTION
**Pull request by vatsalyagoel**
Please take a moment to fill out the following:

Based on #612

Changes Proposed in this pull request:
- Add CancellationToken Support for multi gallery select and Resolve Merge Conflicts

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
I just need to test it to be honest with you :) It is on my list!

**Comment by jamesmontemagno** [comment]
i promise not to have you rebase again lol!

**Comment by chuvakpavel** [comment]
Hello, we are very impressed with your work and your plugin is just super, we would not want to change it to another solution and are ready to wait for you to update and add multisect

**Comment by vatsalyagoel** [comment]
Hi @Happin3ss,

I will try and port this change to not use the ELCImagePicker library. I am not the original author of this PR and it has been floating around for a while. I have tested it on an iPhone X and haven't seen crashes yet. However if it is deprecated then it is definitely a good idea to use a different/native library. @jamesmontemagno hopefully that can be done as part of a future PR and not this one :)

**Comment by jamesmontemagno** [comment]
I think we can pull in what we have here and then rev on it as I will leave it in beta for a long while

**Comment by vatsalyagoel** [comment]
Ready when you are.

**Comment by arggrande** [comment]
Howdy folks, is there an ETA on this being merged into the beta stream? This would be *extremely* useful.

**Comment by arggrande** [comment]
ty <3

**Comment by Happin3ss** [comment]
Finally It came out :) . Maybe I will try to take a look on the deprecation of Asset Library if I have sometime

**Comment by vatsalyagoel** [comment]
<3

**Comment by ManuLin** [comment]
Hi folks,

I really appreciate that these changes have finally been merged into the beta. I just tried to use the updated API (PickPhotosAsync) on Android, however, it seems like I'm not able to actually select more than one picture. Is anyone else having this issue as well?

Best,

Manuel

**Comment by uvirra** [comment]
@ManuLin It's not working for me on Android as well. Do we need to create a new issue for this?

**Comment by jensbrobak** [comment]
It's working almost perfectly on both iOS and Android, UWP; however I experience an null pointer exception error when not selecting any photos from gallery, here is the stack trace:

"  at Plugin.Media.MediaImplementation+<PickPhotosAsync>d__20.MoveNext () [0x0011b] in D:\\a\\1\\s\\src\\M…".

I don't know exactly how to prevent this from happening.

Here is my code:
```
                    mediaFiles = await CrossMedia.Current.PickPhotosAsync();

                    if (mediaFiles != null)
                    {
                        foreach (var mediaFile in mediaFiles)
                        {
                            fileWrappers.Add(new FileWrapper { FileName = Path.GetFileNameWithoutExtension(mediaFile.Path), FileExtension = Path.GetExtension(mediaFile.Path), Stream = await GetStream(mediaFile) });
                        }
                    }
```

- Anyone experiencing the same?

**Comment by chuvakpavel** [comment]
@jensbrobak, i have the same issue, do you found any solution?

**Comment by jensbrobak** [comment]
@chuvakpavel, my quick solution has been to simply surround my code with a try/catch..

**Comment by chuvakpavel** [comment]
@jensbrobak I tried it, but my control for call "gallery select" disabled after this

**Comment by risingworld777** [comment]
@vatsalyagoel  It seems this feature is enabled in v4.2.0.1
Can you let me know how to use it please?

**Comment by SoledadIce** [comment]
> @vatsalyagoel It seems this feature is enabled in v4.2.0.1
> Can you let me know how to use it please?

call PickPhotosAsync() instead of PickPhotoAsync()

**Comment by yemlihaoner** [comment]
Hi guys. I am using **PickPhotosAsync**() in my app. In the emulator it works perfectly. On my phone I am only able to select one picture. I realized that it is upto the **gallery application** that user uses. 

So how can I fix this issue and **make it sure** user will be able to select **multible** pictures? Am I able to force user to use a spesific gallery app such as google photos?

**Comment by atrodriguez88** [comment]
Hello guys  
The same thing happened to me. It does not allow selection in Gallery (Galaxy Store v 10.2.00.16).
Question
When I use **PickPhotosAsync()** it returns me to List but it is not sorted by date or name. Can I handle the order of the selection?

**Pull request merged**
