### PR TITLE
issue-178 -- Factor SaveMediaFileWithOptions logic into its own method to share impl between photo/video

### LINKED ISSUE #308: [UWP] File name and directory name are not getting set correctly for the video taken using StoreVideoOptions
## Bug Information
File name and directory name are not getting set correctly for the video taken using StoreVideoOptions

Version Number of Plugin: 3.0.1
Device Tested On: Microsoft Surface Laptop with Windows 10 and Microsoft Lumia Mobile with Windows 10
Simulator Tested On:
Version of VS: 15.2 (26430.14)
Version of Xamarin: 4.5.0.486 (fec6f88)
Versions of other things you are using:

### Steps to reproduce the Behavior
1. Install MediaPlugin to your Xamarin Forms application
2. Handle Button click to take video specifying StoreVideoOptions with SaveToAlbum, Name and Directory properties set (refer screenshots)
3. Run the application and click on the button to take video.

### Expected Behavior
Video should be captured and stored in the specified directory folder with the specified name.

### Actual Behavior
Video is getting stored in "TempState" directory with File name as "CCapture"

### Code snippet
        private async void Video_Tapped(object sender, EventArgs e)
        {
            await CrossMedia.Current.Initialize();

            if (!CrossMedia.Current.IsCameraAvailable
                || !CrossMedia.Current.IsTakeVideoSupported)
            {
                await DisplayAlert("No camera", "No camera available on the device!", "Ok");
            }

            var file = await CrossMedia.Current.TakeVideoAsync(new StoreVideoOptions
            {
                SaveToAlbum = true,
                Quality = VideoQuality.Medium,
                Directory = "MyProjectFolder",
                Name = $"{DateTime.UtcNow.Ticks}.mp4"
            });

            if (file == null)
            {
                return;
            }

            await DisplayAlert("Video recorded", $"Location: {file.Path}", "Ok");
            file.Dispose();
        }

### Screenshots
mediaplugintakevideocode
videocapturedscreenshot

### PR DESCRIPTION
**Pull request by daniel-packard**
Fixes #308, #178 (UWP ONLY) .

Changes Proposed in this pull request:
- Factor logic to save a media file with directory/filename options into a shared method so Photo/Video support the same options.a

### CODE REVIEW

**Comment by daniel-packard** [comment]
Hey @prashantvc -- Not trying to step on any toes, I just wanted to get your take on this small PR to address #308 and #178  (**note:** UWP only)

Appreciate your time/feedback

thanks!

**Comment by prashantvc** [comment]
@daniel-packard thanks for the PR. I am taking a look at it, will keep you updated :)

**Comment by prashantvc** [comment]
Hey @daniel-packard 
I really appreciate taking your time to submit this PR. All the changes looks good, however we cannot merge this to master yet.

The issue #308 has larger scope of supporting `options` for all media APIs, ie. Pick/Take for Pictures and Videos (for all platforms). I recommend building libraries from the scope, if you want to get this fix in your code base.

**Comment by daniel-packard** [comment]
Sounds good - thanks for taking a look!

**Comment by daniel-packard** [comment]
Hey @prashantvc - if you can give me some guidance on what the scope of the work is, and which branches I can make contributions to - I'd be happy to chip in

**Comment by jamesmontemagno** [comment]
Imma re-open just so I can look at this a bit more.

**Comment by dominic-simplan** [comment]
Hi, any update on this? I am little bit confused what the plans are when this fix will be merged? Is there any workaround until this issue is fixed?

**Comment by daniel-packard** [comment]
Hey @dominic-simplan -- sorry, didn't see this comment in my notifications! 

I think @jamesmontemagno has this on his backburner as something that _may_ be merged, depending on some other outstanding work. 

Our team has been working around this by copying the file _from_ the incorrect location in TempState _to_ the correct destination.

```csharp
// ref: CRS-244 -- currently the video is not stored to the directory we specify
// it is always stored to TempState, so we will copy to Media immediately
// https://github.com/jamesmontemagno/MediaPlugin/issues/178
var fileSystem = AppContainer.Container.Resolve<IFileSystem>();
if (!await fileSystem.FileExistsAsync(CrsFolderPaths.MediaFolderPath, media.LocalFileName))
    await fileSystem.CopyFileToLocalStorageAsync(mediaFile.Path, CrsFolderPaths.MediaFolderPath, media.LocalFileName, skipIfNonExistant: false);
```

... where we've defined the `IFileSystem` interface, and implemented `CopyFileToLocalStorageAsync` on UWP:

```csharp
        public async Task CopyFileToLocalStorageAsync(string filePathToCopy, string destinationFolderPath, string newFileName, bool skipIfNonExistent)
        {
            var destinationFolder = await GetStorageFolderAsync(DataStorageFolder, destinationFolderPath, true).ConfigureAwait(false);

            IStorageFile sourceFile = null;
            try
            {
                sourceFile = await StorageFile.GetFileFromPathAsync(filePathToCopy).AsTask().ConfigureAwait(false);
            }
            catch (FileNotFoundException)
            {
                if (!skipIfNonExistent)
                    throw;//rethrow exception for 
            }

            if (sourceFile != null)
            {
                if (string.IsNullOrWhiteSpace(newFileName))
                    await sourceFile.CopyAsync(destinationFolder).AsTask().ConfigureAwait(false);
                else
                    await sourceFile.CopyAsync(destinationFolder, newFileName).AsTask().ConfigureAwait(false);
            }
        }
```

**Comment by dominic-simplan** [comment]
@daniel-packard thanks for the info and the workaround!

**Comment by daniel-packard** [comment]
@jamesmontemagno , @prashantvc -- let me know if you're still considering this PR. If so, I can bring it up to speed with master (the original file was moved)

Otherwise, we can probably close this one

**Comment by daniel-packard** [comment]
I'm going to close this PR since it's gotten stale

Let me know if there's any interest in reviving the contribution

thanks!

**Pull request closed without merging**
