### PR TITLE
added rotation of image for ios using the existing RotateImage option

### LINKED ISSUE #334: iOS - Implement Rotate Image for Take/Pick and update metadata.
This is via #333

### PR DESCRIPTION
**Pull request by tacoman667**
Please take a moment to fill out the following:

Fixes #334 

Changes Proposed in this pull request:
- Using the existing RotateImage option, this will rotate the image to the original orientation to which the image was captured as.

### CODE REVIEW

**Comment by tacoman667** [comment]
@jamesmontemagno I do not know why the build is failing. It looks like `cake` is failing on it's own and not because of my changes?

**Comment by jamesmontemagno** [comment]
I had recently fixed the build on it.  You may need to just pull from the master: https://github.com/jamesmontemagno/MediaPlugin/commit/96d0795a88f4346f8d1eebf5142846eb4271a63a

**Comment by tacoman667** [comment]
@jamesmontemagno Looks like cake failed again?

**Comment by jamesmontemagno** [comment]
Did you pull the lastest up from master into your fork?

**Comment by tacoman667** [comment]
Sure did.

**Comment by tacoman667** [comment]
image

**Comment by jamesmontemagno** [comment]
Yeah,,,, something else going on with new version of cake :( will try to fix tonight.

**Comment by tacoman667** [comment]
No worries. I just wanted to make you aware in case you weren't notified. :)

**Comment by jamesmontemagno** [comment]
You should be able to pull up the latest and get it building again!

**Comment by tacoman667** [comment]
@jamesmontemagno FYI, looks like all checks passed now. :)

**Comment by tacoman667** [comment]
#333

**Comment by jamesmontemagno** [comment]
Will try to get this in next week now that I am back from 2 weeks of conferences.

**Comment by timbrand** [comment]
I've test this, and it works fine. Thanks!

**Comment by jamesmontemagno** [comment]
So, this actually introduces different functionality compared to the current iteration.

Just looking at my small sample app (that is no XF) when I turn off rotate(old default) then the image I take in portrait is in portrait.

If I turn on rotate, then the image is flipped (because it actually is in the exif data), I am just loading the UIImage from NSData

How are you loading it?

**Comment by jamesmontemagno** [comment]
@tacoman667 ^

**Comment by tacoman667** [comment]
@jamesmontemagno 

The issue I run into is that when I take the image and just push it into a UIView, it works fine. However, I use the `MediaFile` object to get the image as a `Stream` using `GetStream()`, It doesn't persist the XF information. So I get the stream data, push that to an API for storage, of which I pull back through the api upon a refresh, and the image always shows in the original orientation of the device when taken without the metadata telling it what orientation it was supposed to be in. IE, Take image in portrait, the image is actually taken in LeftLandscape, if I recall, but UIImage knows to use the metadata to show it in portrait, where the image pulled from storage or the api doesn't know that information and so it always shows in LeftLandscape.

This happened in `TakePhotoAsync`, and if I remember correctly, in `PickPhotoAsync`. It's all around the storage of the image outside of taking the image and pushing it directly into a view.

The additional method I added actually fixed my issue after taking a picture from the camera much as you do in this library, and rotating the image as I send the data to my API. Then I can get it back and it will be in the expected orientation.

**Comment by jamesmontemagno** [comment]
I think the problem here is when I take a photo now, you are rotating the photo back to the original exif that apple saved it as.

the comments say:
// If rotate image option, then rotate the image to the original orientation it was taken
            // instead of the orientation apple saves it to storage as with the orientation as metadata.

If i take a photo in portrait and have "RotateImage == true" then it shows up as orientation.right, if I take a photo in protrait and have "RotateImage == false" then it shows up in portrait.

So the comments don't actually match the functionality here. What is seems like it should be doing is fixing the metadata really? perhaps?

**Comment by jamesmontemagno** [comment]
I mean if i take a photo, it saves it as "right" i load it into UIImageView and it knows to rotate it, however if you rotate it and still have it set to "right" then it shows up wrong. i am pretty sure.

**Comment by tacoman667** [comment]
My fix is supposed to fix the situation where the stream for the image was stored outside the original data on device. I want to say that I always had this issue if I ever saved the image outside the camera roll. 

It is weird that if you pass no Options into the method for `TakePhotoAsync()`, then `RotateImage` is false, but if you pass in the options but don't set that property, then it defaults to true. Maybe there is a different issue causing what you are experiencing, or at least contributing to this whole craziness?

Maybe we rotate it, and then "reset" the orientation metadata, but I haven't a clue how to do that right now. I am far from an expert in all this. :)

**Comment by jamesmontemagno** [comment]
Yeah, that is what I am testing, you take a photo and then store it locally and display it to your users. 

I have fixed one odditity of it setting RotateImage to false for PickPhotoAsync, but TakePhotoAsync requires options or throws an exception. 

It all seems very strange now when i take anything in portrait with the rotate on. Landscape seems fine.

Can you open up "tests/Media.sln" and test this out because it is very strange.

**Comment by tacoman667** [comment]
@jamesmontemagno I made changes for this in the new PR I linked.

**Pull request merged**
