### PR TITLE
Multi gallery select

### PR DESCRIPTION
**Pull request by dkarzon**
This is still somewhat of a work in progress and I don't expect it to get merged in it's current state. That being said it has been requested by a few people (Issue #153 ).
Would be interested to get some feedback about the approach though and to see if it is something that you would want to include in the library given some work.

For the time being I have created a new method on the IMedia interface that returns `List<MediaFile>` called `PickPhotosAsync` mainly to keep the existing functionality intact.

Android was relatively straight forward however is not supported on every device (depends on the default photos app). This was just a matter of adding the multi flag to the intent and reading the result differently.

iOS was slightly harder since there is no way (that I know about) for the system photo picker to allow multi selection so it's a re-implementation of the photo picker view controller.

I haven't hooked up any of the other platforms yet.

### CODE REVIEW

**Comment by jaspervanmegroot** [comment]
When is this available?

**Comment by dkarzon** [comment]
@jaspervanmegroot Not sure if you read the description of this PR but this may never make it into a real release since it doesn't fit in too well with the existing flow in some cases.
But if you wanted to give that branch a try and give us some feedback that would be helpful.

**Comment by jaspervanmegroot** [comment]
@dkarzon I want to review this but I can't find your branch?

**Comment by dkarzon** [comment]
@jaspervanmegroot You will need to pull it from my fork to get it https://github.com/dkarzon/MediaPlugin/tree/multi-gallery-select
Let me know how you go.

**Comment by jaspervanmegroot** [comment]
@dkarzon I am really new at this but how do I get your branch with NuGet manager?

**Comment by dkarzon** [comment]
@jaspervanmegroot You won't be able to get it from NuGet, you will need to download the source from that branch and build it then include the output in your own project.

**Comment by jaspervanmegroot** [comment]
@dkarzon Okay thank you I got it working but it opens a different select picture screen.  See pictures:
I expected this:
fotoselectscreen

But received this:
fotoselectscreenv2

**Comment by jaspervanmegroot** [comment]
I know what is wrong I think. You don't support iCloud pictures.

**Comment by jBijsterboschNL** [comment]
Any update on this pull request? Will this be released in the near future?

**Comment by CliffCawley** [comment]
@jamesmontemagno Could you weigh in here? Is this something we can get integrated in?

**Comment by alexrainman** [comment]
@jamesmontemagno when this functionality will be merged/released?

**Comment by dipankar2308** [comment]
@jamesmontemagno This is very useful functionality, and would be of great value if available in the Media Plugin.

**Comment by Bohirjon** [comment]
Hey @dkarzon I've tested your changes in some android phones it's working fine but in any Samsung phones (Samsung experience) doesn't work, can you take a look at ?

**Comment by dkarzon** [comment]
@Bohirjon Yes that is a known issue because the Android implementation uses the default gallery app on the device, in the case of Samsung, they have created their own that doesn't support multi selection.

**Comment by tylerAWIS** [comment]
@dkarzon I've just implemented this and it seems to work as expected on the iOS devices I've tested. This is a great addition!

**Comment by ddobrev** [comment]
@dkarzon thank you very much for your work. Could you please rebase it on the latest master? There are some conflicts with moved files and tabs/spaces which I'm afraid would take me too long to resolve.

**Comment by ddobrev** [comment]
@dkarzon also, this pull doesn't actually work. You need to add:

```csharp
pickIntent.SetAction(Intent.ActionGetContent);
pickIntent = Intent.CreateChooser(pickIntent, "Select photos"); // an option for the title?
```

below:

```csharp
pickIntent.PutExtra(Intent.ExtraAllowMultiple, true);
```

in:

```csharp
MediaPickerActivity.OnCreate
```

**Comment by pfaucon** [comment]
@ddobrev  It needs to be verified, but I've reimplemented this on a version rebased to the current master [here](https://github.com/jamesmontemagno/MediaPlugin/pull/612)

**Comment by dkarzon** [comment]
@pfaucon That is great! Do you want me to pull in your updates to this PR or should I just close this one and carry on with that one?

**Comment by pfaucon** [comment]
@dkarzon as you want, I don't have strong feelings one way or another, this PR has more history so it might make more sense to merge it from here. 

It is probably worth doing some basic checking with Android since we don't use it much on our side.  On iOS it seems to work but we just got a report of a crash when clicking outside of the media selector, and then trying to select again afterwards that I will look into tomorrow.

**Comment by aaronclausen** [comment]
I really want this feature too. Keep up the top work guys!

**Comment by jamesmontemagno** [comment]
Clsoing for #612

**Pull request closed without merging**
