### PR TITLE
fixed crash on windows phone 8.1 when user click many times photo button

### PR DESCRIPTION
**Pull request by PiotrBandurski**
Please take a moment to fill out the following:

Fixes # .

Changes Proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Why wouldn't you just use: IsRecording = true; it is already there.

**Comment by PiotrBandurski** [comment]
Becouse this variable is used for video recording and I think that another variable will be better for code clarity. If will be necessary I can change to use IsRecording.

**Comment by PiotrBandurski** [comment]
@jamesmontemagno so I should change it to use IsRecording?

**Comment by jamesmontemagno** [comment]
Closing, as I have implemented myself in next beta.

**Comment by PiotrBandurski** [comment]
... this was my first and last contribution for this repo...

**Comment by jamesmontemagno** [comment]
Thanks for bringing the issue to my attention and I appreciate the PR to fix the issue as well. Got caught up in the holidays and didn't have time to repo and walk through the code.

**Pull request closed without merging**
