### PR TITLE
Request Camera permission, necessary for 7.1

### PR DESCRIPTION
**Pull request by MarcorOnline**
Fixes:
- crash on Android if targetted with SDK 7.1 (android:targetSdkVersion="25")

Changes Proposed in this pull request:
- Runtime request of Camera permission, necessary for 7.1

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
There is no need for the camera permission as your application is not the application that is accessing the camera.

**Comment by MarcorOnline** [comment]
@jamesmontemagno please, try with android:targetSdkVersion="25" on app manifest and you can look a strange behaviour regarding camera permission. The app crashes because has no camera permissions, also if the picture is taken with the external camera application. I know that it's strange, but I've tested on OnePlus 3 (Android 6) and LG G6 (Android 7).

Thanks for your time.

**Comment by jamesmontemagno** [comment]
While I investigate I recommend that you use the permission plugin to handle the permissions yourself as that is highly recommended.

**Comment by jamesmontemagno** [comment]
I just ran it against compile & target SDk of 25 on my Nexus 6P and had no issues at all.

https://developer.android.com/training/camera/photobasics.html

Can you put your stack trace and logcat into gist.github.com

**Comment by MarcorOnline** [comment]
@jamesmontemagno yes, I'm using your plugin to request the permissions, using the code included in my pull request

This is the stack trace:
https://gist.github.com/MarcorOnline/948590ccc56c86d757f49871d10fac7f

This is my sdk declaration in the manifest:
<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="25" />

Thanks for your support

**Comment by jamesmontemagno** [comment]
Can you share your manifest? Did you add a camera permission to it? You shouldn't need to at all, nor does this library.

**Comment by MarcorOnline** [comment]
@jamesmontemagno of course, I've just replaced my package id

https://gist.github.com/MarcorOnline/bbd8ae5c552927f3e6d3069b6509232a

Thanks

**Comment by jamesmontemagno** [comment]
Yes, so if you have the camera permission in your manifest then you would need to request the permission. 

Although you don't need it, so remove it and it will work just fine.

**Comment by jamesmontemagno** [comment]
I have an idea on this to help optimize.

**Comment by MarcorOnline** [comment]
When I've found the bug I didn't have the CAMERA permission on manifest. I've added it to try to solve the problem.
I know that it's a very strange bug... but thats it.

To be sure I've retried:
- uninstalling the app
- removing the CAMERA permission from manifest
- deleting bin and obj
- cleaning and rebuilding

The crash persist...

**Comment by jamesmontemagno** [comment]
Here it is from the source:

https://developer.android.com/reference/android/provider/MediaStore.html#ACTION_IMAGE_CAPTURE

Note: if you app targets M and above and declares as using the CAMERA permission which is not granted, then atempting to use this action will result in a SecurityException.


As you can see it is not required. However, the next beta will now check to see if you did mark the camera permission and try to request.

However you should attempt to check this with the permission plugin.

**Comment by jamesmontemagno** [comment]
Here is also a good SO on it: http://stackoverflow.com/questions/32789027/android-m-camera-intent-permission-bug

**Comment by MarcorOnline** [comment]
@jamesmontemagno yes, I've followed the same your stackoverflow link to understend how to fix my problem. I'm happy to hear that you will introduce a double check for this issue.

Thanks again for your fast support

**Pull request closed without merging**
