### PR TITLE
Refactor ELCAssetTablePicker to be a UICollectionViewController

### PR DESCRIPTION
**Pull request by J-Swift**
Please take a moment to fill out the following:

Cleans up #650

Changes Proposed in this pull request:

`ELCAssetTablePicker`, likely due to its noted age in the original PR, was acting a lot like a poor mans `UICollectionViewController`. I've made it a less-poor mans implementation deriving from CollectionView and tried to clean the API up a bit. This should be easier to maintain and behave less quirky (i.e. not having to listen to rotation changes and manually recalculate layout).

I didn't do this here, but I also think we should unify the single-select vs multi-select codepaths, and not use two different view controllers in the two cases. I assume this wasn't done because the multi-select was just introduced and so is untested? I actually stumbled on this refactor because I was trying to debug a multi-select issue and wasn't aware I was looking at the wrong view controller : )

Also, a disclaimer that I am very new to Xamarin/C#, so please excuse any idiom violations.

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
@vatsalyagoel can you look at this?

**Comment by vatsalyagoel** [comment]
I'm currently travelling. Will have a look once I get back next week. :)

**Comment by J-Swift** [comment]
@vatsalyagoel - pinging here to see if you had a chance to review.

I'd love to get this in so I can look at unifying single/multi-select. I'm not a big fan of the custom modal on tablet, so I'm hoping to get some time to switch that to a 'proper' modal at some point.

**Comment by vatsalyagoel** [comment]
Hi @J-Swift,

I'll go through the changes today. They look good just need to do some more testing :)

**Comment by vatsalyagoel** [comment]
@jamesmontemagno, @J-Swift this looks good to go.

**Pull request merged**
