### PR TITLE
Implemented possibility to save images in an album for iOS

### LINKED ISSUE #149: [Feature Request] Choosing album when taking photo or video.
Hi James,
First I want to congratulate you for the excellent library. 
I decided to write this feature request because I think that it's important and I know several people who are interested in it.
Please let me know what do you think.

## Feature Request:
Allow choosing album when taking photo or video.
Include property Album or AlbumName in StoreCameraMediaOptions and StoreVideoOptions and store the picture/video in this album.

```cs
var pic = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
{
    Name = "Picture",
    SaveToAlbum = true,
    Album = "MyAlbum"
});

var vid = await CrossMedia.Current.TakeVideoAsync(new StoreVideoOptions
{
    Name = "Video",
    SaveToAlbum = true,
    Album = "MyAlbum"
});
```

### PR DESCRIPTION
**Pull request by Genfood**
I finally were able to implement it to save pictures in an album under iOS. This works not for videos but i guess it's very similar to implement.

Fixes #149 .

Changes Proposed in this pull request:
- Added a new property for the name of the album. If this is filled an album will be created. 
- Added function to get the album by the given album name.
- Added action to save the image.
- Creates the album if it doesn't exist.

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
For this, it should be in the block below where it says "SaveToAlbum" it should check if the the user wants to save it is a specific folder or the default. This also would need to be implemented on Android if possible. We should research that.


Could this not be done with ALAssetsLibrary? Something like: http://blog.oskoui-oskoui.com/?p=8510

**Comment by GuteLaune** [comment]
I will fix this.
Should DirectoryName equal to the Album Name?

For me it works well on Android without any changes. I guess the Android gallerys will create the albums for the directorys with images in it.
And I guess every Android distribution will use their own gallery app?

I thought ALAsetsLibrary is deprecated, since iOS 7?

But I will check if I am possible to implement this with the ALAssetsLibrary.

**Comment by jamesmontemagno** [comment]
I could imaging that they want it different. So I think that is fine.

I use ALAssetsLibrary jsut fine to put it in there :)
Maybe should update the code to use the new one for both operations...?

Basically if they set an AlbumName then use it, else the default.

**Comment by GuteLaune** [comment]
I update the code to work with ALAssetLibrary but I wasn’t able to test it for the moment. 
I hope I will be able to test it in the next days...

I could investigate to implement both with PHPhotoLibrary it shouldn’t be a big deal. It’s up to you. I guess the new API would be better for future updates.

I added the property AlbumName like u said.

**Comment by GuteLaune** [comment]
So I implemented both Album saves with PHPhotoLibrary.

I tried to implement it with ALAssetsLibrary but some weird async stuff was going on so it seems not possible for me to do it this way.
I commented the code out so maybe someone else is possible to do it.

For PHPhotoLibrary doesn’t exist a method to get the path of the recently saved photo that’s why the AlbumPath property won’t be filled.
Of course there is a way to get the AlbumPath but I wasn’t able to do this for the moment because it seems a bit complex.
May it helps you anyway.

**Comment by marcominerva** [comment]
Any update on this? I think this feature is really important :-)

**Comment by Genfood** [comment]
Check the code which I implemented it worked for me.

**Comment by marcominerva** [comment]
Thank you, I'll surely take a look at this, but I'm wondering whether it will be merged in the Media Plugin ;-)

**Pull request closed without merging**
