### PR TITLE
Removed an unnecessary picker.Dispose()

### PR DESCRIPTION
**Pull request by Omarkth**
Please take a moment to fill out the following:

Fixes issue number #563.

Changes Proposed in this pull request:
- the picker controller was being disposed twice, and one of the two calls is actually before the picker is really dismissed. so I just removed that.

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Seems like in your comment you also implemented an onDismiss different.... to disposed when on dismiss? will that be in here?

**Comment by Omarkth** [comment]
the different onDismiss was my first fix, but when I realized that the Dispose was actually being called twice, I kept the old onDismiss and only removed the second extra Dispose() call

**Comment by jamesmontemagno** [comment]
Gotcha, i see and saw your comment. Interesting..... will pull in and check out.

**Comment by iupchris10** [comment]
Any word on when this will be deployed to beta?

**Pull request merged**
