### PR TITLE
Fix to  - Only one operation can be active at at time #598

### PR DESCRIPTION
**Pull request by vagrawal1986**
Fixes # .
1. src/Media.Plugin/Android/MediaImplementation.cs
2. src/Media.Plugin/Android/MediaPickerActivity.cs
Changes Proposed in this pull request:
Following **scastria** comment  -

https://github.com/jamesmontemagno/MediaPlugin/issues/598#issuecomment-412937648

"The cause is pretty simple. The media picker uses TaskCompletionSource to turn a callback driven API into Task async/await style. but the code adds a check to make sure that only 1 TaskCompletionSource is active at one time. "
"So whether you click the button twice or do my workflow, in both cases TaskCompletionSource is not null the second time and the exception is thrown."

If we null out the completionSource onDestry of the MediaPicker activity, we can get rid of the bug

### CODE REVIEW

**Comment by vagrawal1986** [comment]
Fixes # .

src/Media.Plugin/Android/MediaImplementation.cs
src/Media.Plugin/Android/MediaPickerActivity.cs
Changes Proposed in this pull request:
Following scastria comment -
#598 (comment)

"The cause is pretty simple. The media picker uses TaskCompletionSource to turn a callback driven API into Task async/await style. but the code adds a check to make sure that only 1 TaskCompletionSource is active at one time. "
"So whether you click the button twice or do my workflow, in both cases TaskCompletionSource is not null the second time and the exception is thrown."

If we null out the completionSource onDestry of the MediaPicker activity, we can get rid of the bug

**Comment by jamesmontemagno** [comment]
There were a lot of changes in the multi-select gallery part, will need to resolve some conflicts or make a new PR here

**Comment by vagrawal1986** [comment]
@jamesmontemagno 
Thanks for looking into this. All conflicts resolved, would greatly appreciate if this can be merged.
Thanks
Also,
I am very new to Github community and this is my first pull request, so pardon any silliness :)

**Comment by Trevonious** [comment]
@vagrawal1986 Do you think this fix would apply to the issues with clicking outside the popup in iOS (see #666)? It looks like the original author of the multi-select feature was seeing the same issue as me, but it seems he thought it was handled (https://github.com/jamesmontemagno/MediaPlugin/issues/598#issuecomment-421259839).

**Comment by vagrawal1986** [comment]
@Trevonious 
The fix I put in only caters droid only as I did not face any issue with iOS at least before multi-select. I have not investigated clicking outside issue on iOS for multi select. But I think this fix should handle the android part of the bug.

**Pull request merged**
